/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QCNhHyYtyBd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function Task() {
  return (
    <div className="flex flex-col min-h-screen p-4">
      <div className="mx-auto max-w-2xl space-y-4">
        <div className="flex flex-col items-center space-y-2">
          <h1 className="font-bold text-3xl">Tasks</h1>
          <div className="flex w-full border-b border-gray-200 dark:border-gray-800" />
        </div>
        <div className="flex w-full">
          <form className="flex w-full items-center space-x-2">
            <Checkbox id="task1" className="self-start" />
            <div className="flex-1">
              <Label htmlFor="task1" className="font-normal">
                Learn about shadcn
              </Label>
            </div>
            <Button type="submit" variant="icon" size="sm">
              <TrashIcon className="h-4 w-4" />
              <span className="sr-only">Delete task</span>
            </Button>
          </form>
        </div>
        <div className="flex w-full">
          <form className="flex w-full items-center space-x-2">
            <Checkbox id="task2" className="self-start" />
            <div className="flex-1">
              <Label htmlFor="task2" className="font-normal">
                Build a todo app
              </Label>
            </div>
            <Button type="submit" variant="icon" size="sm">
              <TrashIcon className="h-4 w-4" />
              <span className="sr-only">Delete task</span>
            </Button>
          </form>
        </div>
        <div className="flex w-full">
          <form className="flex w-full items-center space-x-2">
            <Checkbox id="task3" defaultChecked className="self-start" />
            <div className="flex-1">
              <Label htmlFor="task3" className="font-normal line-through dark:line-through">
                Test the app
              </Label>
            </div>
            <Button type="submit" variant="icon" size="sm">
              <TrashIcon className="h-4 w-4" />
              <span className="sr-only">Delete task</span>
            </Button>
          </form>
        </div>
        <div className="flex w-full">
          <form className="flex w-full items-center space-x-2">
            <Checkbox id="task4" className="self-start" />
            <div className="flex-1">
              <Label htmlFor="task4" className="font-normal">
                Deploy the app
              </Label>
            </div>
            <Button type="submit" variant="icon" size="sm">
              <TrashIcon className="h-4 w-4" />
              <span className="sr-only">Delete task</span>
            </Button>
          </form>
        </div>
        <div className="flex w-full items-center space-x-2">
          <Checkbox id="task5" className="self-start" />
          <div className="flex-1">
            <Input id="task5" placeholder="Add a new task" className="border-0 shadow-none" />
          </div>
          <Button type="submit" variant="outline" className="h-8">
            Add
          </Button>
        </div>
      </div>
    </div>
  )
}

function TrashIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  )
}
